#ifndef _KEY_HANDLE_H
#define _KEY_HANDLE_H
#include "key.h"
#define KEY_TASK_TIME          20
 

typedef enum
{

    ENTER_MENU,
    ENTER_SETS,
    PAGE_ADD,
    PAGE_REDUCU,
    EXIT_MENU,

    S1_TEMP_ADD,
    S1_TEMP_REDUCE,

    S1_TEMP_ADD_FIVE,
    S1_TEMP_REDUCE_FIVE,

    S2_TEMP_ADD,
    S2_TEMP_REDUCE,

    S2_TEMP_ADD_FIVE,
    S2_TEMP_REDUCE_FIVE,

    GET_CHANNEL_1,
    GET_CHANNEL_2,
    GET_CHANNEL_3,

    SET_CHANNEL_1,
    SET_CHANNEL_2,
    SET_CHANNEL_3,

    HANDLE_SELECT,

    SET_WORK_MODE,
    SET_TEMP_UNIT,

    SELECT_S1_CAL,
    SELECT_S2_CAL,
    SELECT_NONE_CAL,
    SET_S1_CAL_TEMP_ADD,
    SET_S1_CAL_TEMP_REDUCE,
    SET_S1_CAL_TEMP_ADD_FIVE,
    SET_S1_CAL_TEMP_REDUCE_FIVE,
    SET_S2_CAL_TEMP_ADD,
    SET_S2_CAL_TEMP_REDUCE,
    SET_S2_CAL_TEMP_ADD_FIVE,
    SET_S2_CAL_TEMP_REDUCE_FIVE,

    SET_SPEAK_MODE,
    SET_TEMP_LOCK,

    SELECT_S1_SLEEP,
    SELECT_S2_SLEEP,
    SELECT_NONE_SLEEP,
    SET_S1_SLEEP_TIME_ADD,
    SET_S1_SLEEP_TIME_REDUCE,
    SET_S1_SLEEP_TIME_ADD_FIVE,
    SET_S1_SLEEP_TIME_REDUCE_FIVE,
    SET_S2_SLEEP_TIME_ADD,
    SET_S2_SLEEP_TIME_REDUCE,
    SET_S2_SLEEP_TIME_ADD_FIVE,
    SET_S2_SLEEP_TIME_REDUCE_FIVE,

    RESET_BE02_VALUE,
    END_EVENT,

} EVENT;

void key_handle(void);
#endif
